# Generated by Django 4.1 on 2022-09-03 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='updated_date',
        ),
    ]
